### ISSUE TITLE
RFC 8615 requirements on registration

### ISSUE THREAD

**Issue by Kevsy** [ietf-wg-httpapi/api-catalog#10]
_from  [AD review](https://mailarchive.ietf.org/arch/msg/httpapi/jNd6HfIC8MLhpD-0bE4S12rmDgs/)_

Section 6:

>From RFC 8615 Section 3, on well-known registration requirements:

   At a minimum, a registration will reference a specification that
   defines the format and associated media type(s) to be obtained by
   dereferencing the well-known URI

which seems to contradict what Section 6 states:

> There is no mandated format for the API Catalog document: the Publisher is free to choose any format that supports the automated discovery, and machine (and human) usage of their APIs.

I cc @mnot  as IANA expert for the Well-Known URIs, hopefully he can weigh in here. (He will have to review this registration request anyway later on).

**Comment by mnot** [comment]
It seems like the right question for the WG to consider is whether it's really interoperable to specify a semantic but allow its payload to be in any format.

Typically, a well-known location will specify at least one format that must be supported, but allow use of other formats (e.g., using content negotiation).

**Comment by richsalz** [comment]
I think they key point is Mark's second comment and that one format must be specified/supported. That's some the WG would need to review/approve, but really should not be controversial. You can propose something here, or on the email list when you're ready, @Kevsy

**Comment by Kevsy** [comment]
Thanks for the helpful feedback, here are the changes I'll include in thePR:

(1) Removed 

`There is no mandated format for the API Catalog document: the Publisher is free to choose any format that supports the automated discovery, and machine (and human) usage of their APIs. However, it is RECOMMENDED to use a linkset {{!RFC9264}} of API endpoints (see {{api-catalog-example-linkset}} for an example).`

...and replaced with:

`The Publisher MUST publish the API Catalog document in the Linkset format application/linkset+json (section 4.2 of {{!RFC9264}}). In addition, the Publisher MAY make additional formats available via content negotiation (section 5.3 of {{!RFC7231}}) to their /.well-known/api-catalog location. A non-exhaustive list of such formats that support the automated discovery, and machine (and human) usage of a Publisher's APIs, is listed below.`

(2) In the `Conformance to RFC8615`  IANA section I've added a `Formats and associated media types` subsection:

`A /.well-known/api-catalog location MUST support the Linkset {{!RFC9264}} format of application/linkset+json, and MAY also support the other formats via content negotiation (section 5.3 of {{!RFC7231}}).`

(3) @mnot , do I need to add the application/linkset+json format in the IANA Considerations section? Or is it sufficient that it is part of the Specification Document?

-- 

I'll include these changes in the PR with the other AD review fixes, but meanwhile any feedback welcome :)

**Comment by Kevsy** [comment]
Included in b738f3de9dbfa8f6451a03601a093ce0de6858b2

**Comment by mnot** [comment]
In the spec should be adequate.

**Comment by fpalombini** [comment]
That looks good, thanks @Kevsy (Side note: you probably need to point to the right sections in 9110 rather than 7231)

@darrelmiller in the mailing list [says](https://mailarchive.ietf.org/arch/msg/httpapi/hvoEfaiRPPxzPKncj3FR2NkJPQ8/):

> I think it would be reasonable to reference the Linkset media type in the well-known registration as a recommendation.  Maybe even a SHOULD.  However, MUST seems like it is going to do more harm than good to me.

which seems to contradict the discussion here... 
I am tempted to say this needs to be agreed on by the WG before the LC, would you agree @richsalz (as chair)?

**Comment by richsalz** [comment]
Yes, the WG needs to confirm anything.  We'll ask @Kevsy to send a note to the list and then we'll ask for discussion and consensus.

**Comment by Kevsy** [comment]
Following discussion on the list I have kept Linkset as a mandatory to implement format in the [latest version]( https://datatracker.ietf.org/doc/draft-ietf-httpapi-api-catalog/)
