### ISSUE TITLE
SECDIR Last Call Review: Section 9 : DoS mitigation

### ISSUE THREAD

**Issue by Kevsy** [ietf-wg-httpapi/api-catalog#39]
_Extracted from Joey Salazar's [SecDir Last Call review](https://mailarchive.ietf.org/arch/msg/httpapi/XGDmbHY8rEjdM91oTipwOneN57M/):_ 

To help mitigate abuse and prevent denial-of-service (DoS) attacks on the API catalog endpoint,
rate-limiting measures could be recommended.

**Comment by richsalz** [comment]
I think that's a geenral concern about overwhelming ANY web offering and don't see why this draft needs it more than anything else. I think making a generic statement is fine.

**Comment by Kevsy** [comment]
Added general statement in Security Considerations.
