### ISSUE TITLE
SECDIR Last Call Review: Section 9 : explore catalog tampering prevention

### ISSUE THREAD

**Issue by Kevsy** [ietf-wg-httpapi/api-catalog#42]
_Extracted from Joey Salazar's [SecDir Last Call review](https://mailarchive.ietf.org/arch/msg/httpapi/XGDmbHY8rEjdM91oTipwOneN57M/):_ 

Considerations on how to verify that catalog content has not been tampered with should be explored.

**Comment by richsalz** [comment]
I think a statement along the lines of to ensure no tampering has been done, use TLS.

**Comment by Kevsy** [comment]
Added to Security Considerations
