### ISSUE TITLE
GENART Last Call Review: change use of HTTP(S)

### ISSUE THREAD

**Issue by Kevsy** [ietf-wg-httpapi/api-catalog#44]
_Extracted from Mallory Knodel's [GENART Last Call review](https://mailarchive.ietf.org/arch/msg/httpapi/qhI_to9cfSkXSCm5vN97NxSG_Xg/):_

Lastly perhaps consider the use of HTTP(S), a new convention-- I haven't
 seen this usage anywhere else in documentation. You could use HTTP/HTTPS, or
 you might controversially perhaps use just HTTPS and describe in the security
 considerations why you are not being explicit about the use of HTTP (given we
 have moved on from this standard 20 years ago).

**Comment by richsalz** [comment]
To address this and Joey’s tampering concern, perhaps just recommend TLS like “TLS SHOULD be used”

**Comment by Kevsy** [comment]
Replaced all `HTTP(S)` with `HTTPS`, checked all URIs use `https://`, and added that 'TLS SHOULD be used' in Security Considerations.
